/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedTripsRouteImport } from './routes/_protected/trips'
import { Route as ProtectedMaintenanceRouteImport } from './routes/_protected/maintenance'
import { Route as ProtectedFuel_expensesRouteImport } from './routes/_protected/fuel_expenses'
import { Route as ProtectedFleetRouteImport } from './routes/_protected/fleet'
import { Route as ProtectedDriversRouteImport } from './routes/_protected/drivers'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAnalyticsRouteImport } from './routes/_protected/analytics'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTripsRoute = ProtectedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMaintenanceRoute = ProtectedMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFuel_expensesRoute = ProtectedFuel_expensesRouteImport.update({
  id: '/fuel_expenses',
  path: '/fuel_expenses',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFleetRoute = ProtectedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDriversRoute = ProtectedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnalyticsRoute = ProtectedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/drivers': typeof ProtectedDriversRoute
  '/fleet': typeof ProtectedFleetRoute
  '/fuel_expenses': typeof ProtectedFuel_expensesRoute
  '/maintenance': typeof ProtectedMaintenanceRoute
  '/trips': typeof ProtectedTripsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/drivers': typeof ProtectedDriversRoute
  '/fleet': typeof ProtectedFleetRoute
  '/fuel_expenses': typeof ProtectedFuel_expensesRoute
  '/maintenance': typeof ProtectedMaintenanceRoute
  '/trips': typeof ProtectedTripsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/analytics': typeof ProtectedAnalyticsRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/drivers': typeof ProtectedDriversRoute
  '/_protected/fleet': typeof ProtectedFleetRoute
  '/_protected/fuel_expenses': typeof ProtectedFuel_expensesRoute
  '/_protected/maintenance': typeof ProtectedMaintenanceRoute
  '/_protected/trips': typeof ProtectedTripsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/drivers'
    | '/fleet'
    | '/fuel_expenses'
    | '/maintenance'
    | '/trips'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/drivers'
    | '/fleet'
    | '/fuel_expenses'
    | '/maintenance'
    | '/trips'
    | '/auth/login'
    | '/auth/signup'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/analytics'
    | '/_protected/dashboard'
    | '/_protected/drivers'
    | '/_protected/fleet'
    | '/_protected/fuel_expenses'
    | '/_protected/maintenance'
    | '/_protected/trips'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/trips': {
      id: '/_protected/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof ProtectedTripsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/maintenance': {
      id: '/_protected/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof ProtectedMaintenanceRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/fuel_expenses': {
      id: '/_protected/fuel_expenses'
      path: '/fuel_expenses'
      fullPath: '/fuel_expenses'
      preLoaderRoute: typeof ProtectedFuel_expensesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/fleet': {
      id: '/_protected/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof ProtectedFleetRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/drivers': {
      id: '/_protected/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof ProtectedDriversRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analytics': {
      id: '/_protected/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedAnalyticsRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAnalyticsRoute: typeof ProtectedAnalyticsRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedDriversRoute: typeof ProtectedDriversRoute
  ProtectedFleetRoute: typeof ProtectedFleetRoute
  ProtectedFuel_expensesRoute: typeof ProtectedFuel_expensesRoute
  ProtectedMaintenanceRoute: typeof ProtectedMaintenanceRoute
  ProtectedTripsRoute: typeof ProtectedTripsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAnalyticsRoute: ProtectedAnalyticsRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedDriversRoute: ProtectedDriversRoute,
  ProtectedFleetRoute: ProtectedFleetRoute,
  ProtectedFuel_expensesRoute: ProtectedFuel_expensesRoute,
  ProtectedMaintenanceRoute: ProtectedMaintenanceRoute,
  ProtectedTripsRoute: ProtectedTripsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
